// lib/ai-tools/agentActionLogTypes.ts
//
// TypeScript types for agent_action_log Supabase table.
// Type-only file — no runtime imports, no Supabase client, no DB calls.
//
// Schema defined in: supabase/migrations/20260603_agent_action_log.sql
// Apply migration manually before using these types in runtime code.

// ─── Enums ────────────────────────────────────────────────────────────────────

export type AgentActionLogStatus =
  | 'draft'             // initial state — record created, not yet sent for review
  | 'pending_approval'  // submitted to manager for review via Approval UI
  | 'approved'          // manager approved — still NOT sent to client automatically
  | 'rejected'          // manager rejected — requires revision or discard
  | 'failed'            // tool/runtime error before reaching approval stage
  | 'archived'          // manually archived — preserved for audit, not active

export type AgentActionType =
  | 'proposal_draft_created'   // createCommercialProposalRuntime completed ok
  | 'proposal_draft_updated'   // draft regenerated for existing record
  | 'proposal_approved'        // manager approved in Approval UI
  | 'proposal_rejected'        // manager rejected in Approval UI
  | 'calculation_run'          // standalone runQuickCalcTool call
  | 'pricing_rules_read'       // standalone runPricingRulesTool call
  | 'kp_draft_generated'       // standalone runGenerateKpDraftTool call
  | 'b2b_quote_draft_created'  // createB2BQuickQuoteRuntime completed ok (B2B Quick Quote skill)
  | 'runtime_completed'        // full orchestrator run recorded (all steps ok)
  | 'error'                    // failed action (tool error or validation failure)
  | (string & {})              // allow future action types without breaking existing code

export type ApprovalStatus =
  | 'not_required'   // approval_required: false
  | 'pending'        // waiting for manager review
  | 'approved'       // explicitly approved
  | 'rejected'       // explicitly rejected

// ─── Safety snapshot ──────────────────────────────────────────────────────────
// Matches CreateCommercialProposalRuntimeSafety from createCommercialProposalRuntime.ts

export type AgentSafetySnapshot = {
  no_db_write:               true
  no_crm_write:              true
  no_client_send:            true
  no_order_create:           true
  no_external_http?:         true
  reads_supabase_via_tools?: boolean
  model_call_executed:       boolean
  model_call_allowed?:       boolean
}

// ─── Approval snapshot ────────────────────────────────────────────────────────
// Stored in approval_snapshot jsonb column when status transitions.

export type AgentApprovalSnapshot = {
  approved_by:    string
  timestamp:      string      // ISO 8601
  manager_notes?: string
  action_taken:   'approved' | 'rejected'
  draft_title?:   string
}

// ─── INSERT type ──────────────────────────────────────────────────────────────
// Used when writing a new record. All required fields must be present.
// id, created_at, updated_at are auto-generated by Supabase.

export type AgentActionLogInsert = {
  // Identity (optional — set by application layer)
  created_by?:  string | null
  approved_by?: string | null

  // Agent metadata — required
  agent_key:     string
  skill_key?:    string | null
  workflow_key?: string | null
  tool_key?:     string | null

  // Action — required
  action_type: AgentActionType
  status?:     AgentActionLogStatus   // default 'draft' (set by DB)

  // Business linkage — all optional
  related_entity_type?: string | null
  related_entity_id?:   string | null
  client_name?:         string | null
  client_phone?:        string | null
  client_email?:        string | null
  amo_lead_id?:         string | null
  calculation_id?:      number | null
  proposal_title?:      string | null

  // Payloads — typed loosely to accept tool response shapes
  input_snapshot?:    Record<string, unknown>
  output_snapshot?:   Record<string, unknown>
  draft_payload?:     Record<string, unknown> | null
  safety_snapshot?:   AgentSafetySnapshot | Record<string, unknown>
  approval_snapshot?: AgentApprovalSnapshot | Record<string, unknown> | null
  error_snapshot?:    Record<string, unknown>[] | null

  // Approval flags — mirror from runtime response
  approval_required?:   boolean   // default true (set by DB)
  can_send_to_client?:  boolean   // default false (set by DB)
  can_write_crm?:       boolean   // default false (set by DB)
  can_create_order?:    boolean   // default false (set by DB)
  approved_at?:         string | null   // ISO 8601; required if status = 'approved'
  rejected_at?:         string | null   // ISO 8601; required if status = 'rejected'
  rejection_reason?:    string | null

  // Diagnostics
  warnings?:            string[]
  errors?:              Array<{ code: string; message: string; field?: string; step?: string }>
  runtime_version?:     string | null
  model_call_executed?: boolean   // default false (set by DB)
  model_name?:          string | null
}

// ─── RECORD type ─────────────────────────────────────────────────────────────
// Full row returned from Supabase SELECT. All fields present and non-optional.

export type AgentActionLogRecord = {
  id:          number
  created_at:  string   // ISO 8601
  updated_at:  string   // ISO 8601

  created_by:  string | null
  approved_by: string | null

  agent_key:    string
  skill_key:    string | null
  workflow_key: string | null
  tool_key:     string | null

  action_type: string
  status:      AgentActionLogStatus

  related_entity_type: string | null
  related_entity_id:   string | null
  client_name:         string | null
  client_phone:        string | null
  client_email:        string | null
  amo_lead_id:         string | null
  calculation_id:      number | null
  proposal_title:      string | null

  input_snapshot:    Record<string, unknown>
  output_snapshot:   Record<string, unknown>
  draft_payload:     Record<string, unknown> | null
  safety_snapshot:   Record<string, unknown>
  approval_snapshot: Record<string, unknown> | null
  error_snapshot:    Record<string, unknown>[] | null

  approval_required:   boolean
  can_send_to_client:  boolean
  can_write_crm:       boolean
  can_create_order:    boolean
  approved_at:         string | null
  rejected_at:         string | null
  rejection_reason:    string | null

  warnings:            string[]
  errors:              Array<Record<string, unknown>>
  runtime_version:     string | null
  model_call_executed: boolean
  model_name:          string | null
}

// ─── UPDATE type (for Approval UI) ───────────────────────────────────────────
// Only the fields that the Approval UI should be allowed to change.

export type AgentActionLogApprovalUpdate = {
  status:           'approved' | 'rejected'
  approved_by?:     string
  approved_at?:     string   // ISO 8601 — required if status = 'approved'
  rejected_at?:     string   // ISO 8601 — required if status = 'rejected'
  rejection_reason?: string
  approval_snapshot?: AgentApprovalSnapshot
  updated_at?:       string  // auto-set by DB trigger
}
