-- Счёт как ЗАПИСЬ розничного контура (раньше счёт был только печатной формой
-- договора, поэтому его нельзя было найти по номеру, выставить на часть суммы
-- и закрыть оплатой).
--
-- Правила:
--  • счёт принадлежит сделке, опционально ссылается на договор;
--  • сумма своя — счёт бывает на предоплату, остаток или монтаж;
--  • оплата закрывает КОНКРЕТНЫЙ счёт (deal_payments.invoice_id), статус
--    «оплачен» выводится из суммы оплат, а не проставляется руками;
--  • номер выдаёт сквозной счётчик, формат С-0001 — как автономер договора.

create table if not exists public.deal_invoices (
  id           bigint generated by default as identity primary key,
  deal_id      bigint not null references public.deals(id) on delete cascade,
  contract_id  bigint references public.contracts(id) on delete set null,
  number       text not null,
  amount       numeric not null default 0,
  purpose      text not null default 'prepay',     -- prepay | balance | install | full
  issued_at    date not null default (now() at time zone 'Europe/Moscow')::date,
  due_at       date,
  status       text not null default 'issued',     -- issued | paid | cancelled
  comment      text,
  created_by   uuid,
  created_by_name text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index if not exists deal_invoices_deal_idx on public.deal_invoices (deal_id, created_at desc);

alter table public.deal_payments add column if not exists invoice_id bigint references public.deal_invoices(id) on delete set null;
create index if not exists deal_payments_invoice_idx on public.deal_payments (invoice_id);

create table if not exists public.deal_invoice_counters (id int primary key, seq int not null default 0);
insert into public.deal_invoice_counters (id, seq) values (1, 0) on conflict (id) do nothing;

-- SECURITY DEFINER: номер выдаёт функция, чтобы два менеджера не получили один
-- и тот же. Права снимаем — зовёт её только сервер сервис-клиентом.
create or replace function public.next_deal_invoice_number()
returns text language plpgsql security definer set search_path = public as $$
declare v int;
begin
  update public.deal_invoice_counters set seq = seq + 1 where id = 1 returning seq into v;
  return 'С-' || lpad(v::text, 4, '0');
end $$;

revoke all on function public.next_deal_invoice_number() from public, anon, authenticated;

alter table public.deal_invoices enable row level security;

drop policy if exists deal_invoices_select on public.deal_invoices;
create policy deal_invoices_select on public.deal_invoices for select to authenticated using (
  exists (select 1 from public.deals d where d.id = deal_invoices.deal_id)
);
