-- ============================================================================
-- Коммерческие предложения (КП). Модуль Продажи → КП.
-- Гибкая схема: ключевые поля колонками (для списка/истории/поиска) + весь
-- разобранный КП в content jsonb (структура подстраивается под визуал КП).
-- Применять в Supabase SQL Editor (авто-раннера миграций в проекте нет).
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.commercial_proposals (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number        text NOT NULL,                          -- КП-2026-001
  client_name   text,
  client_phone  text,
  client_address text,
  object_name   text,                                   -- объект/адрес монтажа
  items         jsonb NOT NULL DEFAULT '[]'::jsonb,      -- [{name,dimensions,quantity,unit_price,sum}]
  subtotal      numeric,
  discount_percent numeric DEFAULT 0,
  total         numeric,
  valid_until   date,
  content       jsonb NOT NULL DEFAULT '{}'::jsonb,      -- полный разобранный КП (под визуал)
  photos        jsonb NOT NULL DEFAULT '[]'::jsonb,      -- пути в приватном bucket
  raw_transcript text,                                   -- последняя голосовая расшифровка
  status        text NOT NULL DEFAULT 'draft',           -- draft | final | sent
  manager_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  manager_name  text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_cp_created_at ON public.commercial_proposals (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_cp_manager   ON public.commercial_proposals (manager_id, created_at DESC);

-- Автонумерация КП: глобальный счётчик, формат 0159-0 (как в существующих КП).
-- Отдельная таблица-счётчик, чтобы номера не зависели от удалений строк.
-- Стартовое значение 158 — следующий номер продолжит текущую последовательность.
CREATE TABLE IF NOT EXISTS public.cp_counters (
  year int PRIMARY KEY,
  seq  int NOT NULL DEFAULT 0
);
INSERT INTO public.cp_counters (year, seq) VALUES (0, 158) ON CONFLICT (year) DO NOTHING;

CREATE OR REPLACE FUNCTION public.next_cp_number()
RETURNS text LANGUAGE plpgsql AS $$
DECLARE v int;
BEGIN
  INSERT INTO public.cp_counters (year, seq) VALUES (0, 1)
  ON CONFLICT (year) DO UPDATE SET seq = public.cp_counters.seq + 1
  RETURNING seq INTO v;
  RETURN lpad(v::text, 4, '0') || '-0';
END $$;

-- RLS: менеджер видит свои КП (или все, если see_all_orders); owner-роли — всё.
-- Публичный bucket под фото/чертежи изделия (попадают в PDF по прямой ссылке).
INSERT INTO storage.buckets (id, name, public) VALUES ('kp-photos', 'kp-photos', true)
ON CONFLICT (id) DO NOTHING;

ALTER TABLE public.commercial_proposals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "cp read own or all" ON public.commercial_proposals;
CREATE POLICY "cp read own or all" ON public.commercial_proposals
  FOR SELECT TO authenticated USING (
    manager_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM public.users u
      WHERE u.id = auth.uid()
        AND (u.role IN ('admin','ceo','commercial') OR u.see_all_orders = true)
    )
  );

DROP POLICY IF EXISTS "cp insert own" ON public.commercial_proposals;
CREATE POLICY "cp insert own" ON public.commercial_proposals
  FOR INSERT TO authenticated WITH CHECK ( manager_id = auth.uid() );

DROP POLICY IF EXISTS "cp update own or admin" ON public.commercial_proposals;
CREATE POLICY "cp update own or admin" ON public.commercial_proposals
  FOR UPDATE TO authenticated USING (
    manager_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role IN ('admin','ceo'))
  );
