-- ============================================================================
-- Договоры + Счета (модуль Продажи → Договор/Счёт). Один договор = один счёт
-- (счёт производен от договора). Изоляция как у КП: менеджер видит только свои,
-- удаляет только admin/ceo.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.contracts (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number        text NOT NULL,                          -- 0158-0
  kp_id         bigint REFERENCES public.commercial_proposals(id) ON DELETE SET NULL,
  date          date,
  customer_type text NOT NULL DEFAULT 'individual',     -- individual | company
  customer      jsonb NOT NULL DEFAULT '{}'::jsonb,      -- ФИО/паспорт/адрес ИЛИ реквизиты
  spec          jsonb NOT NULL DEFAULT '[]'::jsonb,      -- позиции (из КП)
  total         numeric,
  make_sum      numeric,                                 -- стоимость изготовления
  install_sum   numeric,                                 -- стоимость монтажа
  product_kind  text DEFAULT 'mirror',                   -- mirror|shower|loft|welded
  make_days     int DEFAULT 15,
  install_days  int DEFAULT 5,
  vat_rate      numeric DEFAULT 5,
  content       jsonb NOT NULL DEFAULT '{}'::jsonb,       -- полный разобранный договор (доп. поля)
  status        text NOT NULL DEFAULT 'draft',           -- draft | sent | signed
  manager_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  manager_name  text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_contracts_created ON public.contracts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contracts_manager ON public.contracts (manager_id, created_at DESC);

-- Автономер договоров: глобальный счётчик, формат 0158-0. Старт 156.
CREATE TABLE IF NOT EXISTS public.contract_counters (year int PRIMARY KEY, seq int NOT NULL DEFAULT 0);
INSERT INTO public.contract_counters (year, seq) VALUES (0, 156) ON CONFLICT (year) DO NOTHING;

CREATE OR REPLACE FUNCTION public.next_contract_number()
RETURNS text LANGUAGE plpgsql AS $$
DECLARE v int;
BEGIN
  INSERT INTO public.contract_counters (year, seq) VALUES (0, 1)
  ON CONFLICT (year) DO UPDATE SET seq = public.contract_counters.seq + 1
  RETURNING seq INTO v;
  RETURN lpad(v::text, 4, '0') || '-0';
END $$;

ALTER TABLE public.contracts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "contracts read own or owner" ON public.contracts;
CREATE POLICY "contracts read own or owner" ON public.contracts
  FOR SELECT TO authenticated USING (
    manager_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role IN ('admin','ceo'))
  );

DROP POLICY IF EXISTS "contracts insert own" ON public.contracts;
CREATE POLICY "contracts insert own" ON public.contracts
  FOR INSERT TO authenticated WITH CHECK ( manager_id = auth.uid() );

DROP POLICY IF EXISTS "contracts update own or owner" ON public.contracts;
CREATE POLICY "contracts update own or owner" ON public.contracts
  FOR UPDATE TO authenticated USING (
    manager_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role IN ('admin','ceo'))
  );

DROP POLICY IF EXISTS "contracts delete owner only" ON public.contracts;
CREATE POLICY "contracts delete owner only" ON public.contracts
  FOR DELETE TO authenticated USING (
    EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role IN ('admin','ceo'))
  );
